format = """
$os\
$directory\
$git_branch\
$git_status\
$nodejs\
$rust\
$golang\
$php\
$time\
$line_break\
$character"""

[os]
disabled = false
format = "[$symbol ]($style)"
style = "bg:#769ff0 fg:#e3e5e5"

[os.symbols]
Arch = ""

[directory]
style = "bg:#394260 fg:#e3e5e5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ".../"

[git_branch]
symbol = ""
style = "bg:#212736 fg:#769ff0"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#212736)]($style)'

[git_status]
style = "bg:#212736 fg:#769ff0"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#212736)]($style)'

[nodejs]
symbol = ""
style = "bg:#1d2230 fg:#769ff0"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#1d2230)]($style)'

[rust]
symbol = ""
style = "bg:#1d2230 fg:#769ff0"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#1d2230)]($style)'

[golang]
symbol = ""
style = "bg:#1d2230 fg:#769ff0"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#1d2230)]($style)'

[php]
symbol = ""
style = "bg:#1d2230 fg:#769ff0"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#1d2230)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:#33658A fg:#e3e5e5"
format = '[[ 󰥔 $time ](fg:#e3e5e5 bg:#33658A)]($style)'

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
